-- This file has been intentionally cleared.
-- All database schema is managed exclusively via Flyway migrations
-- located at: backend/neobank360app/src/main/resources/db/migration/
--
-- To inspect the schema, run:
--   SELECT * FROM flyway_schema_history;
